### ISSUE TITLE
Error in new updated version 1.0.12

### ISSUE THREAD

**Issue by rameshvishnoi90904** [gm0t/react-sticky-el#10]
i am using es5 and after todays update, i started getting error.
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method.

previously in sticky.js and index.js,
there was
module.exports = exports['default'];
and now above line is not present

**Comment by gm0t** [comment]
Hi Ramesh! 
Thank you for the feedback, yes my bad - cjs build was broken.
It is fixed in 1.0.13 version, please update.
