### ISSUE TITLE
Stop stick when reach element

### ISSUE THREAD

**Issue by nuno-correia-rodrigues** [gm0t/react-sticky-el#15]
Hello, i´m trying to stop the behaviour of stickiness of one element when reach a parent element, not to hide, just be fixed above that element, is possible? 

thanks in advance :)

**Comment by gm0t** [comment]
Hi, please take a look at example with **hideOnBoundaryHit=false**
http://rawgit.com/gm0t/react-sticky-el/master/dist/examples/index.html
Is it what you want to get?

**Comment by nuno-correia-rodrigues** [comment]
Hi, before all thanks for the quick reply :).
I took a look into the link, is quite similiar as my main objective, but not total :) i will made a fork and made send an link to show what i want to solve :)

**Comment by gm0t** [comment]
Ok, I will be glad to help :)

**Comment by nuno-correia-rodrigues** [comment]
Tks for your help :) i solve the problem
