### ISSUE TITLE
Loosing NavItem active className change

### ISSUE THREAD

**Issue by shaibe** [gm0t/react-sticky-el#17]
When using the Sticky in combination with Bootstarp NavItem, clicking the NavItem will not update the className as active...

`<div>
		  <div className='sweet-loading'>
    	  	<BounceLoader loading={this.state.loading} color={'#123abc'} />
    	  </div>
		  <Tab.Container id="left-tabs" defaultActiveKey={0} >
		    <Row className="clearfix">
		      <Col sm={3}>
		      <div>
		      <Sticky stickyClassName={"sticy-pills"}>
			      {arr.map((item, key) =>
			        <Nav bsStyle="pills" key={key +'_1'}>
			          <NavItem eventKey={key} key={key + '_2'} >
			          	{item.title}
			          </NavItem>
			        </Nav>
			       )}
		      </Sticky>
		      </div>
		      </Col>
		      <Col sm={8}>
		      <Tab.Content animation>
		      	{arr.map((item, key) =>
		          <Tab.Pane mountOnEnter eventKey={key} key={key + '_3'}>
		          <ServiceJsonEditor serviceName={item.serviceName} key={key + '_4'}/> 
		          </Tab.Pane>
		      	 )}
		        </Tab.Content>
		      </Col>
		    </Row>
		  </Tab.Container>
		  </div>`

**Comment by gm0t** [comment]
Hi @shaibe, fixed in 1.0.15.
