### ISSUE TITLE
"transform translateZ(0px)" breaks z-index

### ISSUE THREAD

**Issue by ggregoire** [gm0t/react-sticky-el#20]
Hi,

With `transform translateZ(0px)`:

![screen shot 2018-01-11 at 13 20 28](https://user-images.githubusercontent.com/591804/34840286-7cbde08c-f6d2-11e7-8327-c2cdcfa96a8a.png)

Without:

![screen shot 2018-01-11 at 13 21 12](https://user-images.githubusercontent.com/591804/34840295-81e047c6-f6d2-11e7-9b7a-31f4d32ff741.png)

The HTML code:

![screen shot 2018-01-11 at 13 23 33](https://user-images.githubusercontent.com/591804/34840364-c4f1bda6-f6d2-11e7-9a84-3b4999df6853.png)

It's a [react-dates](https://github.com/airbnb/react-dates) element on the screenshot, but I noticed the same issue with [react-select](https://github.com/JedWatson/react-select) when the dropdown is opened.

Thanks for the help.

**Comment by gm0t** [comment]
Hi @ggregoire ! I can add option, to remove "translateZ", but it doesn't seem right to me.
Could you please create an example at jsbin.com or any other online sandbox?

**Comment by ggregoire** [comment]
Hi @gm0t ! Here is an example: https://codesandbox.io/s/xlxoj057jq

If you open the select, you'll see the issue with the graph. In removing `transform: translateZ(0px)` in the Google Chrome Inspector, it fixes the issue.

There is probably another solution but I didn't find it. :/

**Comment by gm0t** [comment]
@ggregoire you can fix this problem by adding z-index style to .sticky:
```
.sticky {
  z-index: 1;
}
```
an updated example:
https://codesandbox.io/s/2w9mj46jyr

**Comment by ggregoire** [comment]
Doesn't seem to work:

![screen shot 2018-01-16 at 09 20 52](https://user-images.githubusercontent.com/591804/34996289-c8c691a2-fa9e-11e7-8025-1d6a7b444e85.png)

**Comment by gm0t** [comment]
Yeh, I missed 'non-sticky' case :(
I have updated the example (https://codesandbox.io/s/2w9mj46jyr)
You can add className for Sticky:
```
.sticky-selector {
  position: relative;
  z-index: 1;
}
```

or you can simply pass styles directly:

```
<Sticky style={{ zIndex: 2, position: "relative" }} >
  <div>content</div>
</Sticky>
```

**Comment by ggregoire** [comment]
It works, thanks! :)
