### ISSUE TITLE
Prop to disable sticking

### ISSUE THREAD

**Issue by chacestew** [gm0t/react-sticky-el#24]
Hi there - first, thanks for the library! I've found it much simpler to add to our project than react-sticky so far.

Would it make sense to add an `unstick` prop to explicitly turn off the sticky styles? Currently I've achieved this by setting a conditional `stickyClassName` that adds `position: relative !important` (ugly!).

Of course it is possible to just render `<Sticky />` conditionally, but I am trying to avoid this to keep the DOM tree consistent for server rendering and have fewer conditions with nested JSX.

**Comment by gm0t** [comment]
Hi @chacestew! I think it will be a very useful feature.
May be we can call it `disabled`, what do you think?

**Comment by mecenasy** [comment]
hi the library is great, although it is very lacking in the ability to disable the sticky.
 
the thought that this function is called disabled is great when you can expect it because I miss it very much

**Comment by gm0t** [comment]
`disabled` prop is now available in version 1.0.17

**Comment by zakirsajib** [comment]
how to disable the sticky in mobile?
