### ISSUE TITLE
[Question] A way to not hide element when hit bottom?

### ISSUE THREAD

**Issue by Dranac** [gm0t/react-sticky-el#3]
Hi! Thanks for this sticky element it looks great. 

There's only one thing which is a bit annoying in my case, i just do not want the sticky element to be hidden when it hit the bottom.

(In a easier way to understand, in the exemple page, i would like the `Header` part not to disappear when it hit the `footer` part, i would like it to stay visible and at his position)

Did i miss something ? Or can you help me ?

Thanks

**Comment by gm0t** [comment]
Hi! Thanks for the feedback!
I've added a new option "hideOnBoundaryHit", it should solve you problem.
