### ISSUE TITLE
Make transform: translateZ(0px) optional

### ISSUE THREAD

**Issue by paulincai** [gm0t/react-sticky-el#41]
Hi,

Example: LinkedIn. The grid has 3 columns. I am considering the third for this emphasis.
The 3rd column sticks as the middle one is being scrolled down. However on a mobile you cannot view 2-3 columns and probably for this case the stickiness is entirely not required on mobile.
My suggestion is to "activate" the transformation only on mobile or on demand. The issue I am facing (still keeping in mind a layout like LinkedIn) is that a Modal declared inside a sticky component doesn't expand to full screen, it takes the size of the sticky container. Without the transformation everything is fine. I am not able to disable the inline styling off the component by overwriting that transformation.

I attached 3 images: first: shows the Photos sticky container before selecting a photo. The second show the gallery modal running inside the sticky container. The third is the modal when I disable the transformation from Chrome console
![1](https://user-images.githubusercontent.com/26188915/49006461-9608c600-f182-11e8-97c4-2feb43ea086d.png)
![2](https://user-images.githubusercontent.com/26188915/49006462-9608c600-f182-11e8-9d32-9a6160593ffe.png)
![3](https://user-images.githubusercontent.com/26188915/49006541-c81a2800-f182-11e8-8c94-31d1d3f8c16e.png)

Thank you

**Comment by paulincai** [comment]
Ok, it looks that I could disable the inline styling using a class prop. Good to go but still feel the option should/could be a ... feature.

**Comment by johnhunter** [comment]
👍 for this option. The transform [creates a positioning context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) that messes with the tooltips we use within the sticky header

**Comment by johnhunter** [comment]
The original reason for including the `translateZ` was for issues on iOS Safari https://github.com/gm0t/react-sticky-el/blob/ecfd1de28bca4ab540d6065c76bee1fccfa2de6d/dist/react-sticky-el.js#L721-L724

Not sure if [that issue](http://stackoverflow.com/questions/32875046) is still a problem but it would be great if we could make it optional.

**Comment by gm0t** [comment]
Can be disabled with `isIOSFixEnabled: false`
