### ISSUE TITLE
onFixedToggle callback has the wrong fixed state

### ISSUE THREAD

**Issue by martinbroos** [gm0t/react-sticky-el#49]
When using the callback and the element becomes sticky the argument of the callback returns `false` and when no longer being sticky it returns `true`. 

My guess is  that function is passed a reference to the old state and it should be newState.fixed.
https://github.com/gm0t/react-sticky-el/blob/master/src/sticky.js#L260

**Comment by gm0t** [comment]
yeah 🤦‍♂ ... fixed in 2.0.1
thanks a lot for reporting this one! :)
