### ISSUE TITLE
When sticky element has different styling the holder height causes layout shifts

### ISSUE THREAD

**Issue by martinbroos** [gm0t/react-sticky-el#50]
My initial element has an height of 100 px, this will be set as min-height when the element becomes fixed. This is correct.

However my stuck element needs to become less tall so I shrink my font-size and make sure long titles don't wrap. 

After a sec the min-height of my holder element gets updated to the height of my stuck element which causes a layout shift. 

Is there a way to deal with this? In opinion the min-height should not be calculated by the stuck element.

**Comment by kupe517** [comment]
@martinbroos  I was able to solve this by using the prop 
`positionRecheckInterval="100"`
on the Sticky component. I don't think it's ideal since it's checking frequently but it solves the problem until a better solution is implemented. 

I'm not sure why min-height needs to be set inline in the first place...

**Comment by martinbroos** [comment]
@kupe517 thanks, I'm gonna try this. But my guess is that it will still calculate the height of the sticky element and not restore the initial height of the holder element that causes the layout to shift.

**Comment by gm0t** [comment]
hey  @martinbroos , could you please create an example that I can use to reproduce this issue?

**Comment by martinbroos** [comment]
I will try to setup something real soon. Thanks for wanting to look into it.

**Comment by gm0t** [comment]
@martinbroos feel free to use - https://codesandbox.io/s/react-sticky-el-example-fn0ev as a bootstrap

**Comment by martinbroos** [comment]
@gm0t I created a quick example of the problem. See: https://codesandbox.io/s/react-sticky-el-example-qiijz?file=/src/App.js

It's not super clear because the scroll to anchors won't work in codesandbox. But you can still see what's happening when you keep the code inspector open. The min height of the wrapper element gets changed when the header becomes sticky. And since this header has no subtitle and smaller font-size it will result in a small layout shift. Not very visible but it becomes extra clear when there are anchors on the page. Because then when you click them before the header is sticky it will result in the wrong end location. 

In my view the holder of sticky component should be only calculated once before it becomes sticky as its use is to keep the layout flow in check when the child becomes fixed.

**Comment by gm0t** [comment]
Awesome! @martinbroos thanks a lot! I will take a look at it a bit later today and see what could be done

**Comment by gm0t** [comment]
hey @martinbroos, sorry it took me a bit longer than I thought, but I've finally added a new property `dontUpdateHolderHeightWhenSticky`, that should fix your issue.

you can see an example here:
https://rawgit.com/gm0t/react-sticky-el/master/storybook-static/index.html?path=/story/advanced--dont-update-holder-height-when-sticky

**Comment by martinbroos** [comment]
Great this wil definitely help. Will try it in my project soon. Thanks again for your work on this library!

**Comment by martinbroos** [comment]
Finally tested this and works as expected in the project where I had issues with v1.1.1
So thanks again 👍

**Comment by namlq93** [comment]
How can I change the width in stickyStyle?

**Comment by tyumen-777** [comment]
> dontUpdateHolderHeightWhenSticky

Does it work on version 2.0.9? Because my header still jumping after adding this property...

**Comment by gm0t** [comment]
Hi @tyumen-777 , should've been fixed... can you create a sandbox example to demonstrate the problem that you have?
