### ISSUE TITLE
React StrictMode issues

### ISSUE THREAD

**Issue by kachkaev** [gm0t/react-sticky-el#51]
I tried switching from [`react-sticky`](https://github.com/captivationsoftware/react-sticky) to this library, hoping to make my app compatible with React’s [`<StrictMode />`](https://reactjs.org/docs/strict-mode.html) and therefore the upcoming [Concurrent mode](https://reactjs.org/docs/concurrent-mode-intro.html).

However, after installing `react-sticky-el@1.1.0` and refactoring, I saw these warnings:

```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is
not recommended and may indicate bugs in your code. See
https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code
  to use memoization techniques or move it to static getDerivedStateFromProps.
  Learn more at: https://fb.me/react-derived-state

Please update the following components: Sticky
```

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed
an instance of Sticky which is inside StrictMode. Instead, add a ref directly
to the element you want to reference. Learn more about using refs safely here:
https://fb.me/react-strict-mode-find-node
    in div (created by Sticky)
```

It’d be great to be able to use a version of `react-sticky-el` that’s compatible with StrictMode!

**Comment by gm0t** [comment]
Hi @kachkaev , it took me a bit longer than I expected, but I've finally managed to publish a new version that should be compatible with StrictMode :)
