### ISSUE TITLE
React does not recognize the `stickyStyle` prop on a DOM element.

### ISSUE THREAD

**Issue by yocmen** [gm0t/react-sticky-el#57]
Hi, I got this error trying to add some style to the sticker

```React does not recognize the `stickyStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `stickystyle` instead.``` 

The previous version was good just with the style prop.

PD: I am upgrading to v2 now and I need put scrollElement="window" and boundaryElement=".main_wrapper" because if not give an error, so the default values for this is not working too. 

Thanks in advance for your work.

**Comment by gm0t** [comment]
Argh... Yeah my bad :( 
I'll try to fix it today

**Comment by gm0t** [comment]
Fixed in `2.0.2`
