### ISSUE TITLE
Move eslint-plugin-react and flow-bin to devDependencies?

### ISSUE THREAD

**Issue by jefftmills** [gm0t/react-sticky-el#70]
I have dozens of dependencies in my app that depend on these 2 modules, but react-sticky-el is the only one that has either of them in their production dependencies, so I wonder if that's a mistake. The eslint plugin seems obvious to me but I don't know anything about flow-bin.

Including flow-bin as a production dependency adds 78 MB to the node_modules footprint of this otherwise very small module, so it would be really good to remove it if it's not needed for production.

**Comment by gm0t** [comment]
@jefftmills yep, that's a very unfortunate mistake :) fixed in **2.0.8**, thanks for raising it!

**Comment by jefftmills** [comment]
Thanks for fixing it so soon.

I found this while analyzing the disk footprint of our large web app and found a couple of similar unfortunate mistakes in our own package.json, too.

**Comment by jefftmills** [comment]
Hi Mikhail, can you publish this new version 2.0.8 to npm so folks can start using this new optimized distribution?

**Comment by gm0t** [comment]
Hi @jefftmills, 
Oh... 🤦  published now, sorry for the delay I completely missed that step
I should definitely spend some time automating this step
