### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by lcvbeek** [gm0t/react-sticky-el#8]
Hi all,

I'm getting this error consistently on any scroll event, after unmounting the parent component.

`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at Array.Sticky._this.checkPosition (sticky.js:113)
    at listener.cb (events.js:30)`

FYI, sticky.js:113 is this line:
`var holderRect = _this.refs.holder.getBoundingClientRect(),`

It should remove the scroll eventListener after unmounting, correct? Am I missing something? Do I need to specifically unmount the Sticky element? Anyone else run into this problem?

I'm using a classname as boundaryElement, since using an ID gave me another error. After installing I got two folders in my `node_modules`, `lib` and `es`. And it's reading from the `es` folder, which seems to be outdated. There's an error in `es/helpers/find.js:33`: it's trying to return `window.getElementById`. The same file in the `lib` folder however uses `document` and works fine. But when I build the project it automatically uses the `es` folder...

Any help would be appreciated!

**Comment by lcvbeek** [comment]
Hah, just found an easy workaround for both errors..

`import Sticky from 'react-sticky-el/lib';`

It now seems to succesfully remove the event listener.

**Comment by gm0t** [comment]
Hi! Thanks for feedback, yeah, there was a problem with build.
I published a new version 1.0.11 which fixes this problem :)
