### ISSUE TITLE
got defaultProps remove warning when used with react 18

### ISSUE THREAD

**Issue by j-joker** [gm0t/react-sticky-el#92]
Warning: Sticky: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

**Comment by 0xboga** [comment]
+1 can we get a PR for this ?

**Comment by eremenko1** [comment]
up

**Comment by Oxicode** [comment]
+1

**Comment by ramsaysewell** [comment]
+1

**Comment by e-dewailly** [comment]
Pull Request #95
